CREATE OR ALTER VIEW [dbo].[vwFaturamentoOS] AS

SELECT
	CONVERT(INT,TOS.N_OS) AS 'OS',
	CASE
		WHEN TNF.NUMERO IS NULL THEN TNFSe.NUMERO_NF
		ELSE TNF.NUMERO
	END AS 'NF',
	TNF.VL_TOTAL_NF AS 'Valor da NF',
	CASE
		WHEN TNF.NUMERO IS NULL THEN NULL 
		ELSE COUNT(TOS.N_OS) OVER(PARTITION BY TNF.NUMERO) 
	END AS 'Nº de OS na NF',
	CASE
		WHEN (TNFI.VL_TOTAL + TNFI.VL_IPI) IS NULL THEN TNFSe.VL_TOTAL
		ELSE (TNFI.VL_TOTAL + TNFI.VL_IPI)
	END AS 'Valor Médio da OS',
	TORI.TOTAL_GERAL_VENDA_COM_IPI AS 'Valor Orçado',
	CASE
		WHEN TNFSe.VL_TOTAL IS NOT NULL THEN (TORI.TOTAL_GERAL_VENDA_COM_IPI - (SUM(TNFSe.VL_TOTAL) OVER (PARTITION BY TOS.N_OS)))
		WHEN (TORI.TOTAL_GERAL_VENDA_COM_IPI - (SUM(TNFI.VL_TOTAL + TNFI.VL_IPI) OVER (PARTITION BY TOS.N_OS))) < 1 THEN 0
		WHEN (TORI.TOTAL_GERAL_VENDA_COM_IPI - (SUM(TNFSe.VL_TOTAL) OVER (PARTITION BY TOS.N_OS))) < 1 THEN 0
		WHEN (SUM(TNFI.VL_TOTAL + TNFI.VL_IPI) OVER (PARTITION BY TOS.N_OS)) IS NULL THEN TORI.TOTAL_GERAL_VENDA_COM_IPI
		ELSE ROUND((TORI.TOTAL_GERAL_VENDA_COM_IPI - (SUM(TNFI.VL_TOTAL + TNFI.VL_IPI) OVER (PARTITION BY TOS.N_OS))),2)
	END AS 'Valor Restante a Faturar',
	CASE
		WHEN CONVERT(DATE,TNF.DT_EMISSAO) IS NULL THEN (SELECT CONVERT(DATE,DT_EMISSAO) FROM TNOTA_FISCAL WHERE NUMERO = TNFSe.NUMERO_NF)
		ELSE CONVERT(DATE,TNF.DT_EMISSAO)
	END AS 'Data de Emissão da NF',
	DATEPART(wk, TNF.DT_EMISSAO) AS 'Semana de Emissão da NF',
	TOR.CLIENTE AS 'Cliente',
	TOS.U_PLANEJADOR_DO_PROJETO AS 'Carteirista'
FROM
	TORCAMENTO_ITENS AS TORI

INNER JOIN (SELECT * FROM TORCAMENTO WHERE COD_EMPRESA = 1) AS TOR
	ON TORI.COD_ORCAMENTO = TOR.CODIGO

RIGHT JOIN (SELECT * FROM TOS WHERE COD_EMPRESA = 1 AND N_OS NOT LIKE 'E%' AND APROVADO = 1 AND CANCELADO = 0 /*AND YEAR(DT_APROVACAO) >= 2021 AND N_OS NOT IN ('284', '285', '360', '361', '362')*/) AS TOS
	ON TORI.GUID_LINHA = TOS.GUID_ORCAMENTO

FULL JOIN (SELECT * FROM TNOTA_FISCAL_ITEM WHERE COD_EMPRESA = 1 AND NUMERO_NF NOT IN (11269, 11496, 11562)) AS TNFI
	ON TORI.GUID_LINHA = TNFI.GUID_ORCAMENTO
		FULL JOIN (SELECT * FROM TNOTA_FISCAL WHERE COD_EMPRESA = 1 AND NUMERO NOT IN  (11269, 11496, 11562) AND VL_TOTAL_NF IS NOT NULL AND VL_TOTAL_NF <> 0) AS TNF
			ON TNFI.NUMERO_NF = TNF.NUMERO
				FULL JOIN (SELECT * FROM TNOTA_FISCAL_SERVICO WHERE COD_EMPRESA = 1) AS TNFSe
					ON TORI.GUID_LINHA = TNFSe.GUID_ORCAMENTO --AND TNF.NUMERO = TNFSe.NUMERO_NF --AND TOS.GUID_ORCAMENTO = TNFSe.GUID_ORCAMENTO

/*INNER JOIN (SELECT * FROM TNATU_OP WHERE COD_EMPRESA = 1 AND TIPO = 'S' AND CODIGO NOT IN ('5201', '5202', '5205', '5206', '5207', '5208', '5209', '5210', '5410', '5411', '5412', '5413', '5503', '5553', '5555', '5556', '5660', '5661', '5662', '5918', '5919', '5921', '5925', '6201', '6202', '6208', '6209', '6210', '6410', '6411', '6412', '6413', '6503', '6553', '6555', '6556', '6660', '6661', '6662', '6918', '6919', '6921', '7201', '7202', '7210', '7211', '7553', '7556')) 
																							AS TNATU_OP
	ON TNFI.CFOP = TNATU_OP.CODIGO OR TNF.CFOP = TNATU_OP.CODIGO OR TNFSe.CFOP = TNATU_OP.CODIGO*/

WHERE
	TOS.N_OS IS NOT NULL
--	TORI.COD_EMPRESA = 1 OR
--	TORI.COD_EMPRESA IS NULL


GO


